//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.6.3
//     from Assets/05.InputAction/UIInputAction.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @UIInputAction: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @UIInputAction()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""UIInputAction"",
    ""maps"": [
        {
            ""name"": ""UIActionMap"",
            ""id"": ""cf0d8730-5555-4567-be4d-6fe53b6ba88c"",
            ""actions"": [
                {
                    ""name"": ""ShowMouseCursor"",
                    ""type"": ""Button"",
                    ""id"": ""8b3d2bc0-c67c-43ac-9a23-800f3861e310"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""be8c5ca4-3153-4b6a-9d01-01a9bedae330"",
                    ""path"": ""<Keyboard>/alt"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShowMouseCursor"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // UIActionMap
        m_UIActionMap = asset.FindActionMap("UIActionMap", throwIfNotFound: true);
        m_UIActionMap_ShowMouseCursor = m_UIActionMap.FindAction("ShowMouseCursor", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // UIActionMap
    private readonly InputActionMap m_UIActionMap;
    private List<IUIActionMapActions> m_UIActionMapActionsCallbackInterfaces = new List<IUIActionMapActions>();
    private readonly InputAction m_UIActionMap_ShowMouseCursor;
    public struct UIActionMapActions
    {
        private @UIInputAction m_Wrapper;
        public UIActionMapActions(@UIInputAction wrapper) { m_Wrapper = wrapper; }
        public InputAction @ShowMouseCursor => m_Wrapper.m_UIActionMap_ShowMouseCursor;
        public InputActionMap Get() { return m_Wrapper.m_UIActionMap; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(UIActionMapActions set) { return set.Get(); }
        public void AddCallbacks(IUIActionMapActions instance)
        {
            if (instance == null || m_Wrapper.m_UIActionMapActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_UIActionMapActionsCallbackInterfaces.Add(instance);
            @ShowMouseCursor.started += instance.OnShowMouseCursor;
            @ShowMouseCursor.performed += instance.OnShowMouseCursor;
            @ShowMouseCursor.canceled += instance.OnShowMouseCursor;
        }

        private void UnregisterCallbacks(IUIActionMapActions instance)
        {
            @ShowMouseCursor.started -= instance.OnShowMouseCursor;
            @ShowMouseCursor.performed -= instance.OnShowMouseCursor;
            @ShowMouseCursor.canceled -= instance.OnShowMouseCursor;
        }

        public void RemoveCallbacks(IUIActionMapActions instance)
        {
            if (m_Wrapper.m_UIActionMapActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IUIActionMapActions instance)
        {
            foreach (var item in m_Wrapper.m_UIActionMapActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_UIActionMapActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public UIActionMapActions @UIActionMap => new UIActionMapActions(this);
    public interface IUIActionMapActions
    {
        void OnShowMouseCursor(InputAction.CallbackContext context);
    }
}
